// constants/premadeMathCollections.ts
export const PREMADE_COLLECTIONS_RAW = [
  // {
  //   id: "premade-test",
  //   name: "TEST",
  //   archived: false,
  //   entries: [
  //     { id: "test-1", latex: `{}` },        
  //     { id: "test-2", latex: `[]` },        
  //     { id: "test-3", latex: `` },        
  //     { id: "test-4", latex: `x` },        
  //     { id: "test-5", latex: `{y}` },        
  //     { id: "test-6", latex: `\\{\\}` },        
  //     { id: "test-7", latex: `\\[\\]` },        
  //   ],
  // },
  {
    id: "premade-structures",
    name: "🏗️ Structures",
    archived: false,
    isPremade: true,
    entries: [
      { id: "struc-1", latex: `\\iiiint _{}^{}` },
      { id: "struc-2", latex: `\\iiint _{}^{}` },
      { id: "struc-3", latex: `\\iint _{}^{}` },
      { id: "struc-4", latex: `\\int _{}^{}` },
      { id: "struc-5", latex: `\\overset{}{}` },
      { id: "struc-6", latex: `\\sqrt[]{} ` },
      { id: "struc-7", latex: `\\sum _{}^{}` },
      { id: "struc-8", latex: `\\text{}` },
      { id: "struc-9", latex: `\\underset{}{}` },
      { id: "struc-10", latex: `\\frac{}{}` },
      { id: "struc-11", latex: `\\actsymb[][]{}{}[]` },
      { id: "struc-12", latex: `_{}^{}{}_{}^{}` },
      { id: "struc-13", latex: `⌈{}⌉` },
      { id: "struc-14", latex: `|{}|` },
      { id: "struc-15", latex: `⌊{}⌋` },
      { id: "struc-16", latex: `[{}]` },
      { id: "struc-17", latex: `\\{\\}` },
      { id: "struc-18", latex: `({})` },
    ],
  },
  {
    id: "premade-calculus",
    name: "Calculus",
    archived: false,
    isPremade: true,
    entries: [
      { id: "calc-1", latex: `\\int_a^b f(x) \\, dx` },
      { id: "calc-2", latex: `\\frac{d}{dx} f(x)` },
      { id: "calc-3", latex: `\\lim_{x \\to a} f(x)` },
      { id: "calc-4", latex: `\\nabla \\cdot \\mathbf{F}` },
      { id: "calc-5", latex: `\\nabla \\times \\mathbf{F}` },
      { id: "calc-6", latex: `\\frac{\\partial f}{\\partial x}` },
      { id: "calc-7", latex: `\\sum_{n=1}^\\infty a_n` },
      { id: "calc-8", latex: `\\int \\sin x \\, dx` },
      { id: "calc-9", latex: `\\int e^x \\, dx` },
      { id: "calc-10", latex: `\\frac{d^2 y}{dx^2}` },
      { id: "calc-11", latex: `\\frac{\\partial^2 f}{\\partial x^2}` },
      { id: "calc-12", latex: `\\int_0^\\infty e^{-x} \\, dx` },
      { id: "calc-13", latex: `\\oint_C \\mathbf{F} \\cdot d\\mathbf{r}` },
      { id: "calc-14", latex: `\\frac{d}{dt} \\int_{a(t)}^{b(t)} f(x,t) \\, dx` },
      { id: "calc-15", latex: `\\lim_{h \\to 0} \\frac{f(x+h) - f(x)}{h}` },
    ],
  },
  {
    id: "premade-logic",
    name: "Logic",
    archived: false,
    isPremade: true,
    entries: [
      { id: "logic-1", latex: `\\forall x \\in X, P(x)` },
      { id: "logic-2", latex: `\\exists x \\in X, P(x)` },
      { id: "logic-3", latex: `P \\implies Q` },
      { id: "logic-4", latex: `P \\land Q` },
      { id: "logic-5", latex: `P \\lor Q` },
      { id: "logic-6", latex: `\\neg P` },
      { id: "logic-7", latex: `P \\iff Q` },
      { id: "logic-8", latex: `\\vdash P` },
      { id: "logic-9", latex: `\\models P` },
      { id: "logic-10", latex: `\\bot` },
      { id: "logic-11", latex: `\\top` },
      { id: "logic-12", latex: `\\therefore P` },
    ],
  },
  {
    id: "premade-probability",
    name: "Probability & Statistics",
    archived: false,
    isPremade: true,
    entries: [
      { id: "prob-1", latex: `P(A)` },
      { id: "prob-2", latex: `P(A \\mid B)` },
      { id: "prob-3", latex: `\\mathbb{E}[X]` },
      { id: "prob-4", latex: `\\mathrm{Var}(X)` },
      { id: "prob-5", latex: `\\mathrm{Cov}(X,Y)` },
      { id: "prob-6", latex: `X \\sim \\mathcal{N}(\\mu, \\sigma^2)` },
      { id: "prob-7", latex: `\\hat{\\theta}` },
      { id: "prob-8", latex: `\\sum_{i=1}^n X_i` },
      { id: "prob-9", latex: `\\int_{-\\infty}^\\infty f_X(x) \\, dx = 1` },
      { id: "prob-10", latex: `\\mathrm{CDF}_X(x) = P(X \\leq x)` },
      { id: "prob-11", latex: `\\mathrm{PDF}_X(x) = \\frac{d}{dx} \\mathrm{CDF}_X(x)` },
    ],
  },
  {
    id: "greek-letters",
    name: "Greek Letters",
    archived: false,
    isPremade: true,
    entries: [
      { id: "greek-alpha", latex: `\\alpha` },
      { id: "greek-beta", latex: `\\beta` },
      { id: "greek-gamma", latex: `\\gamma` },
      { id: "greek-delta", latex: `\\delta` },
      { id: "greek-epsilon", latex: `\\epsilon` },
      { id: "greek-zeta", latex: `\\zeta` },
      { id: "greek-eta", latex: `\\eta` },
      { id: "greek-theta", latex: `\\theta` },
      { id: "greek-iota", latex: `\\iota` },
      { id: "greek-kappa", latex: `\\kappa` },
      { id: "greek-lambda", latex: `\\lambda` },
      { id: "greek-mu", latex: `\\mu` },
      { id: "greek-nu", latex: `\\nu` },
      { id: "greek-xi", latex: `\\xi` },
      { id: "greek-pi", latex: `\\pi` },
      { id: "greek-rho", latex: `\\rho` },
      { id: "greek-sigma", latex: `\\sigma` },
      { id: "greek-tau", latex: `\\tau` },
      { id: "greek-upsilon", latex: `\\upsilon` },
      { id: "greek-phi", latex: `\\phi` },
      { id: "greek-chi", latex: `\\chi` },
      { id: "greek-psi", latex: `\\psi` },
      { id: "greek-omega", latex: `\\omega` },

      // Capital letters
      { id: "greek-Gamma", latex: `\\Gamma` },
      { id: "greek-Delta", latex: `\\Delta` },
      { id: "greek-Theta", latex: `\\Theta` },
      { id: "greek-Lambda", latex: `\\Lambda` },
      { id: "greek-Xi", latex: `\\Xi` },
      { id: "greek-Pi", latex: `\\Pi` },
      { id: "greek-Sigma", latex: `\\Sigma` },
      { id: "greek-Upsilon", latex: `\\Upsilon` },
      { id: "greek-Phi", latex: `\\Phi` },
      { id: "greek-Psi", latex: `\\Psi` },
      { id: "greek-Omega", latex: `\\Omega` },
    ],
  },
  {
    id: "premade-linalg",
    name: "Linear Algebra",
    archived: false,
    isPremade: true,
    entries: [
      { id: "linalg-1", latex: `\\mathbf{v} = \\begin{bmatrix} v_1 \\\\ v_2 \\\\ \\vdots \\\\ v_n \\end{bmatrix}` },
      { id: "linalg-2", latex: `\\mathbf{A} = [a_{ij}]` },
      { id: "linalg-3", latex: `\\mathbf{I}_n` },
      { id: "linalg-4", latex: `\\mathbf{0}` },
      { id: "linalg-5", latex: `\\mathbf{1}` },
      { id: "linalg-6", latex: `\\mathrm{diag}(d_1, d_2, \\dots, d_n)` },
      { id: "linalg-7", latex:  `\\mathbf{A} + \\mathbf{B}` },
      { id: "linalg-8", latex:  `c\\mathbf{v}` },
      { id: "linalg-9", latex:  `\\mathbf{A}\\mathbf{v}` },
      { id: "linalg-10", latex: `\\mathbf{A}\\mathbf{B}` },
      { id: "linalg-11", latex: `\\mathbf{A}^\\top` },
      { id: "linalg-12", latex: `\\mathbf{A}^{-1}` },
      { id: "linalg-13", latex: `\\|\\mathbf{v}\\|` },
      { id: "linalg-14", latex: `\\mathbf{v} \\cdot \\mathbf{w} = \\mathbf{v}^\\top \\mathbf{w}` },
      { id: "linalg-15", latex: `\\mathbf{v} \\otimes \\mathbf{w}` },
      { id: "linalg-16", latex: `\\mathbf{A}\\mathbf{x} = \\mathbf{b}` },
      { id: "linalg-17", latex: `\\mathbf{A}\\mathbf{x} = \\mathbf{0}` },
      { id: "linalg-18", latex: `\\mathrm{rank}(\\mathbf{A})` },
      { id: "linalg-19", latex: `\\mathrm{null}(\\mathbf{A})` },
      { id: "linalg-20", latex: `\\ker(\\mathbf{A})` },
      { id: "linalg-21", latex: `\\mathrm{col}(\\mathbf{A})` },
      { id: "linalg-22", latex: `\\mathrm{row}(\\mathbf{A})` },
      { id: "linalg-23", latex: `\\dim(\\mathrm{null}(\\mathbf{A})) + \\mathrm{rank}(\\mathbf{A}) = n` },
      { id: "linalg-24", latex: `\\mathrm{span}\\{\\mathbf{v}_1, \\dots, \\mathbf{v}_k\\}` },
      { id: "linalg-25", latex: `\\{\\mathbf{v}_1, \\dots, \\mathbf{v}_k\\}` },
      { id: "linalg-26", latex: `\\dim(V)` },
      { id: "linalg-27", latex: `\\mathbf{P}^{-1} \\mathbf{A} \\mathbf{P}` },
      { id: "linalg-28", latex: `[\\mathbf{v}]_{\\mathcal{B}}` },
      { id: "linalg-29", latex: `\\det(\\mathbf{A})` },
      { id: "linalg-30", latex: `\\det(\\mathbf{A}\\mathbf{B}) = \\det(\\mathbf{A})\\det(\\mathbf{B})` },
      { id: "linalg-31", latex: `\\det(\\mathbf{A}^{-1}) = \\frac{1}{\\det(\\mathbf{A})}` },
      { id: "linalg-32", latex: `\\mathbf{A} \\mathbf{v} = \\lambda \\mathbf{v}` },
      { id: "linalg-33", latex: `\\mathrm{eig}(\\mathbf{A})` },
      { id: "linalg-34", latex: `\\mathbf{A} = \\mathbf{PDP}^{-1}` },
      { id: "linalg-35", latex: `\\mathbf{A}^k = \\mathbf{PD}^k \\mathbf{P}^{-1}` },
      { id: "linalg-36", latex: `\\mathrm{trace}(\\mathbf{A}) = \\sum \\lambda_i` },
      { id: "linalg-37", latex: `\\mathrm{proj}_{\\mathbf{u}}(\\mathbf{v}) = \\frac{\\mathbf{u} \\cdot \\mathbf{v}}{\\|\\mathbf{u}\\|^2} \\mathbf{u}` },
      { id: "linalg-38", latex: `\\mathbf{u} \\perp \\mathbf{v}` },
      { id: "linalg-39", latex: `\\mathbf{Q}^\\top \\mathbf{Q} = \\mathbf{I}` },
      { id: "linalg-40", latex: `\\mathbf{P} = \\mathbf{A}(\\mathbf{A}^\\top \\mathbf{A})^{-1} \\mathbf{A}^\\top` },
      { id: "linalg-41", latex: `\\mathbf{A} = \\mathbf{QR}` },
      { id: "linalg-42", latex: `\\mathbf{A} = \\mathbf{LU}` },
      { id: "linalg-43", latex: `\\mathbf{A} = \\mathbf{U} \\Sigma \\mathbf{V}^\\top` },
      { id: "linalg-44", latex: `\\mathbf{x}^\\top \\mathbf{A} \\mathbf{x}` },
      { id: "linalg-45", latex: `\\mathbf{A}^\\top = \\mathbf{A}` },
      { id: "linalg-46", latex: `\\mathbf{A}^\\top = \\mathbf{A}^{-1}` },
      { id: "linalg-47", latex: `\\mathbf{A} = \\mathbf{A}^\\top = \\overline{\\mathbf{A}}` },
      { id: "linalg-48", latex: `A_{ij}` },
      { id: "linalg-49", latex: `\\delta_{ij}` },
      { id: "linalg-50", latex: `\\mathbf{e}_i` },
      { id: "linalg-51", latex: `\\begin{bmatrix} a_{11} & a_{12} & a_{13} \\\\ a_{21} & a_{22} & a_{23} \\end{bmatrix}` },
      { id: "linalg-52", latex: `\\begin{bmatrix} a_{11} & a_{12} \\\\ a_{21} & a_{22} \\\\ a_{31} & a_{32} \\end{bmatrix}` }, 
      { id: "linalg-53", latex: `\\begin{bmatrix} a_{11} & a_{12} & a_{13} & a_{14} \\\\ a_{21} & a_{22} & a_{23} & a_{24} \\\\ a_{31} & a_{32} & a_{33} & a_{34} \\\\ a_{41} & a_{42} & a_{43} & a_{44} \\end{bmatrix}` },
      { id: "linalg-54", latex: `\\begin{bmatrix} a_{11} & a_{12} & a_{13} & a_{14} & a_{15} \\\\ a_{21} & a_{22} & a_{23} & a_{24} & a_{25} \\\\ a_{31} & a_{32} & a_{33} & a_{34} & a_{35} \\\\ a_{41} & a_{42} & a_{43} & a_{44} & a_{45} \\\\ a_{51} & a_{52} & a_{53} & a_{54} & a_{55} \\end{bmatrix}` },
      { id: "linalg-55", latex: `\\begin{matrix} a_{11} & a_{12} \\\\ a_{21} & a_{22} \\end{matrix}` },
      { id: "linalg-56", latex: `\\begin{pmatrix} a_{11} & a_{12} \\\\ a_{21} & a_{22} \\end{pmatrix}` },
      { id: "linalg-57", latex: `\\begin{bmatrix} a_{11} & a_{12} \\\\ a_{21} & a_{22} \\end{bmatrix}` },
      { id: "linalg-58", latex: `\\begin{Bmatrix} a_{11} & a_{12} \\\\ a_{21} & a_{22} \\end{Bmatrix}` },
      { id: "linalg-59", latex: `\\begin{vmatrix} a_{11} & a_{12} \\\\ a_{21} & a_{22} \\end{vmatrix}` },
      { id: "linalg-60", latex: `\\begin{Vmatrix} a_{11} & a_{12} \\\\ a_{21} & a_{22} \\end{Vmatrix}` },
      { id: "linalg-61", latex: `\\vec{v}` },
    ],
  },
  {
    id: "premade-actuarial",
    name: "Actuarial Science",
    archived: false,
    isPremade: true,
    entries: [
      { id: "act-1", latex: `{\\mathrm{M}}_{X}(t)` },
      { id: "act-2", latex: `\\actsymb[t][]{L}{e}[\\underline{2}]` },
      { id: "act-3", latex: `\\actsymb[t][]{\\bar{k}}{x}[]` },
      { id: "act-4", latex: `\\actsymb[][]{(h\\mu )}{x+t}[(j)](u)` },
      { id: "act-5", latex: `H(x;\\alpha ,\\beta ,{x}_{0})` },
      { id: "act-6", latex: `\\actsymb[k][]{F}{}[]` },
      { id: "act-7", latex: `\\actsymb[][]{\\mathring{e}}{x:\\angl{n}}[]` },
      { id: "act-8", latex: `{\\hat{B}}_{x+t}^{(3)}` },
      { id: "act-9", latex: `\\actsymb[][]{A}{x:\\angl{n}}[]` },
      { id: "act-10", latex: `\\actsymb[][]{\\bar{a}}{\\joint{{x}_{1}{x}_{2}{x}_{3}}}[]` },
      { id: "act-11", latex: `\\actsymb[][]{\\bar{a}}{x|y}[]` },
      { id: "act-12", latex: `\\actsymb[][2]{\\ddot{a}}{xy:\\angl{n}}[]` },
      { id: "act-13", latex: `\\mu_x^{(d)}` },
      { id: "act-14", latex: `\\mu_x^{(i)}` },
      { id: "act-15", latex: `\\mu_x^{(w)}` },
      { id: "act-16", latex: `\\mu_x^{(j)}(t)` },
      { id: "act-17", latex: `\\mu_x^{(\\tau)}(t)` },
      { id: "act-18", latex: `\\mu_{xy}(t)` },
      { id: "act-19", latex: `\\mu_{\\joint{xy}}(t)` },
      { id: "act-20", latex: `\\mu(x, u)` },
      { id: "act-21", latex: `\\pi_h` },
      { id: "act-22", latex: `\\pi_t` },
      { id: "act-23", latex: `\\rho` },
      { id: "act-24", latex: `\\tau` },
      { id: "act-25", latex: `\\phi(x)` },
      { id: "act-26", latex: `\\phi(x, u)` },
      { id: "act-27", latex: `\\Psi(u)` },
      { id: "act-28", latex: `\\tilde{\\Psi}(u)` },
      { id: "act-29", latex: `\\Psi(u, t)` },
      { id: "act-30", latex: `\\Psi(u; w)` },
      { id: "act-31", latex: `\\tilde{\\Psi}(u; w)` },
      { id: "act-32", latex: `\\omega` },
      { id: "act-33", latex: `X_i` },
      { id: "act-34", latex: `X(\\theta)` },
      { id: "act-35", latex: `y(s, s + m)` },
      { id: "act-36", latex: `Y(t, n)` },
      { id: "act-37", latex: `z_t` },
      { id: "act-38", latex: `\\actsymb[m]{Z}{t}` },
      { id: "act-39", latex: `\\alpha` },
      { id: "act-40", latex: `\\alpha(m)` },
      { id: "act-41", latex: `\\bar{\\alpha}` },
      { id: "act-42", latex: `α` },
      { id: "act-43", latex: `\\alpha^{\\text{CRVM}}` },
      { id: "act-44", latex: `\\beta` },
      { id: "act-45", latex: `\\beta(m)` },
      { id: "act-46", latex: `\\bar{\\beta}` },
      { id: "act-47", latex: `β` },
      { id: "act-48", latex: `\\beta^{\\text{CRVM}}` },
      { id: "act-49", latex: `\\beta(x, u)` },
      { id: "act-50", latex: `\\Gamma(\\alpha)` },
      { id: "act-51", latex: `\\delta` },
      { id: "act-52", latex: `\\delta_t` },
      { id: "act-53", latex: `\\theta` },
      { id: "act-54", latex: `\\lambda(t)` },
      { id: "act-55", latex: `\\lambda(t, n)` },
      { id: "act-56", latex: `\\Lambda` },
      { id: "act-57", latex: `\\Lambda_h` },
      { id: "act-58", latex: `\\mu(x)` },
      { id: "act-59", latex: `\\mu_x(t)` },
      { id: "act-60", latex: `\\actsymb[k][]{\\bar{W}}{}[](\\actsymb[][]{A}{x:\\angl{n}}[])` },
      { id: "act-61", latex: `\\actsymb[k][]{\\bar{W}}{}[](\\actsymb[][]{A}{x}[])` },
      { id: "act-62", latex: `\\actsymb[k][h]{\\bar{W}}{}[](\\actsymb[][]{A}{x}[])` },
      { id: "act-63", latex: `(x)` },
      { id: "act-64", latex: `\\actsymb[][]{(Wa)}{t}[]` },
      { id: "act-65", latex: `\\actsymb[k][h]{W}{x}[]` },
      { id: "act-66", latex: `\\actsymb[k][]{W}{x:\\angl{n}}[]` },
      { id: "act-67", latex: `\\actsymb[k][]{W}{x}[]` },
      { id: "act-68", latex: `\\actsymb[k][]{W}{}[]` },
      { id: "act-69", latex: `W_t` },
      { id: "act-70", latex: `W_i` },
      { id: "act-71", latex: `w(x)` },
      // { id: "act-72", latex: `` },
    ],
  },
];
