// constants/premadeMathCollections.ts
export const PREMADE_COLLECTIONS_RAW = [
  // {
  //   id: "premade-test",
  //   name: "TEST",
  //   archived: false,
  //   entries: [
  //     { id: "test-1", latex: `{}` },        
  //     { id: "test-2", latex: `[]` },        
  //     { id: "test-3", latex: `` },        
  //     { id: "test-4", latex: `x` },        
  //     { id: "test-5", latex: `{y}` },        
  //     { id: "test-6", latex: `\\{\\}` },        
  //     { id: "test-7", latex: `\\[\\]` },        
  //   ],
  // },
  {
    id: "premade-structures",
    name: "🏗️ Structures",
    archived: false,
    isPremade: true,
    entries: [
      { id: "struc-0", latex: `\\int _{}^{}` },
      { id: "struc-1", latex: `\\iint _{}^{}` },
      { id: "struc-2", latex: `\\iiint _{}^{}` },
      { id: "struc-3", latex: `\\iiiint _{}^{}` },
      { id: "struc-4", latex: `\\oint _{}^{}` },
      { id: "struc-5", latex: `\\overset{}{}` },
      { id: "struc-6", latex: `\\sqrt[]{} ` },
      { id: "struc-7", latex: `\\sum _{}^{}` },
      { id: "struc-8", latex: `\\text{}` },
      { id: "struc-9", latex: `\\underset{}{}` },
      { id: "struc-10", latex: `\\frac{}{}` },
      { id: "struc-11", latex: `\\binom{}{}` },
      { id: "struc-12", latex: `\\actsymb[][]{}{}[]` },
      { id: "struc-13", latex: `_{}^{}{}_{}^{}` },
      { id: "struc-14", latex: `⌈{}⌉` },
      { id: "struc-15", latex: `|{}|` },
      { id: "struc-16", latex: `⌊{}⌋` },
      { id: "struc-17", latex: `[{}]` },
      { id: "struc-18", latex: `\\{\\}` },
      { id: "struc-19", latex: `({})` },
      { id: "struc-20", latex: `\\begin{Vmatrix}{}\\end{Vmatrix}` },
    ],
  },
  {
    id: "premade-calculus",
    name: "Calculus",
    archived: false,
    isPremade: true,
    entries: [
      { id: "calc-1", latex: `\\delta x` },
      { id: "calc-2", latex: `\\Delta x` },
      { id: "calc-3", latex: `\\infty` },
      { id: "calc-4", latex: `\\sum_{n=i}^{k}{a}_{n}` },
      { id: "calc-5", latex: `\\sum_{n=i}^{\\infty }{a}_{n}` },
      { id: "calc-6", latex: `\\begin{Vmatrix}x-y\\end{Vmatrix}` },
      { id: "calc-7", latex: `(x,y)` },
      { id: "calc-8", latex: `\\underset{x\\to \\infty }{\\lim }` },
      { id: "calc-9", latex: `\\underset{x\\to {a}^{+}}{\\lim }` },
      { id: "calc-10", latex: `\\underset{x\\to {a}^{-}}{\\lim }` },
      { id: "calc-11", latex: `\\underset{x\\uparrow a}{\\lim }` },
      { id: "calc-12", latex: `\\underset{x\\downarrow a}{\\lim }` },
      { id: "calc-13", latex: `\\min (A)` },
      { id: "calc-14", latex: `\\max (A)` },
      { id: "calc-15", latex: `\\inf (A)` },
      { id: "calc-16", latex: `\\sup (A)` },
      { id: "calc-17", latex: `\\liminf {a}_{n}` },
      { id: "calc-18", latex: `\\limsup {a}_{n}` },
      { id: "calc-19", latex: `f'(x)` },
      { id: "calc-20", latex: `f"(x)` },
      { id: "calc-21", latex: `{f}^{(n)}(x)` },
      { id: "calc-22", latex: `\\frac{d}{dx}` },
      { id: "calc-23", latex: `\\frac{{d}^{n}}{d{x}^{n}}` },
      { id: "calc-24", latex: `{f}_{x}` },
      { id: "calc-25", latex: `\\frac{\\partial }{\\partial x}` },
      { id: "calc-26", latex: `\\frac{{\\partial }^{n}}{\\partial {x}^{n}}` },
      { id: "calc-27", latex: `{\\partial }_{x}` },
      { id: "calc-28", latex: `{\\nabla }_{v}` },
      { id: "calc-29", latex: `\\partial ` },
      { id: "calc-30", latex: `\\Delta ` },
      { id: "calc-31", latex: `\\nabla \\cdot \\mathbf{F}` },
      { id: "calc-32", latex: `\\nabla \\times \\mathbf{F}` },
      { id: "calc-33", latex: `{|}_{x=a}` },
      { id: "calc-34", latex: `{[]}_{a}^{b}` },
      { id: "calc-35", latex: `\\int_{a}^{b}f(x)\\,dx` },
      { id: "calc-36", latex: `\\int_{}^{}f(x)\\,dx` },
      { id: "calc-37", latex: `\\int_{C}^{}f(\\mathbf{r})\\,ds` },
      { id: "calc-38", latex: `\\int_{C}^{}f(z)\\,dz` },
      { id: "calc-39", latex: `\\oint_{C}^{}f(z)\\,dz` },
      { id: "calc-40", latex: `\\int_{C}^{}\\mathbf{f}(\\mathbf{r})\\cdot d\\mathbf{r}` },
      { id: "calc-41", latex: `\\iint_{D}^{}f\\,dA` },
      { id: "calc-42", latex: `\\iint_{D}^{}f(\\mathbf{r})\\,dS` },
      { id: "calc-43", latex: `\\iiint_{D}^{}f\\,dV` },
      { id: "calc-44", latex: `\\rightarrow ` },
      { id: "calc-45", latex: `\\Rightarrow ` },
      { id: "calc-46", latex: `\\downarrow ` },
      { id: "calc-47", latex: `\\Downarrow ` },
      { id: "calc-48", latex: `\\leftarrow ` },
      { id: "calc-49", latex: `\\Leftarrow ` },
      { id: "calc-50", latex: `\\uparrow ` },
      { id: "calc-51", latex: `\\Uparrow ` },
      { id: "calc-52", latex: `\\leftrightarrow ` },
      { id: "calc-53", latex: `\\Leftrightarrow ` },
      { id: "calc-54", latex: `\\equiv ` },
      { id: "calc-55", latex: `\\sim ` },
      { id: "calc-56", latex: `\\ll ` },
      { id: "calc-57", latex: `\\gg ` },
      { id: "calc-58", latex: `\\in ` },
      { id: "calc-59", latex: `\\log (\\log x)` },
      { id: "calc-60", latex: `\\log x` },
      { id: "calc-61", latex: `{x}_{}^{c}` },
      { id: "calc-62", latex: `x\\log x` },
      { id: "calc-63", latex: `{x}_{}^{2}` },
      { id: "calc-64", latex: `{a}_{}^{x}` },
      { id: "calc-65", latex: `n!` },
      { id: "calc-66", latex: `{x}_{}^{x}` },
      { id: "calc-67", latex: `\\mathrm{sgn}(x)` },
      { id: "calc-68", latex: `\\mathrm{atan2}(y,x)` },
      { id: "calc-69", latex: `\\mathrm{B}(x,y)` },
      { id: "calc-70", latex: `\\mathrm{\\Gamma}(x)` },
      { id: "calc-71", latex: `\\mathrm{sinc}(x)` },
      { id: "calc-72", latex: `\\mathrm{Si}(x)` },
      { id: "calc-73", latex: `\\mathrm{erf}(x)` },
      { id: "calc-74", latex: `\\zeta (s)` },
      { id: "calc-75", latex: `f\\ast g` },
      { id: "calc-76", latex: `\\delta (x)` },
      { id: "calc-77", latex: `H(x)` },
      { id: "calc-78", latex: `\\mathcal{L}\\{f\\}` },
      { id: "calc-79", latex: `{\\mathcal{L}}_{}^{-1}\\{f\\}` },
      { id: "calc-80", latex: `\\mathcal{F}\\{f\\}` },
      { id: "calc-81", latex: `\\hat{f}` },
      { id: "calc-4", latex: `\\int _{}^{}` },
    ],
  },
  {
    id: "premade-logic",
    name: "Logic",
    archived: false,
    isPremade: true,
    entries: [
      { id: "logic-1", latex: `\\forall x \\in X, P(x)` },
      { id: "logic-2", latex: `\\exists x \\in X, P(x)` },
      { id: "logic-3", latex: `P \\implies Q` },
      { id: "logic-4", latex: `P \\land Q` },
      { id: "logic-5", latex: `P \\lor Q` },
      { id: "logic-6", latex: `\\neg P` },
      { id: "logic-7", latex: `P \\iff Q` },
      { id: "logic-8", latex: `\\vdash P` },
      { id: "logic-9", latex: `\\models P` },
      { id: "logic-10", latex: `\\bot` },
      { id: "logic-11", latex: `\\top` },
      { id: "logic-12", latex: `\\therefore P` },
    ],
  },
  {
    id: "premade-probability",
    name: "Probability & Statistics",
    archived: false,
    isPremade: true,
    entries: [
      { id: "prob-1", latex: `P(A)` },
      { id: "prob-2", latex: `P(A \\mid B)` },
      { id: "prob-3", latex: `\\mathbb{E}[X]` },
      { id: "prob-4", latex: `\\mathrm{Var}(X)` },
      { id: "prob-5", latex: `\\mathrm{Cov}(X,Y)` },
      { id: "prob-6", latex: `X \\sim \\mathcal{N}(\\mu, \\sigma^2)` },
      { id: "prob-7", latex: `\\hat{\\theta}` },
      { id: "prob-8", latex: `\\sum_{i=1}^n X_i` },
      { id: "prob-9", latex: `\\int_{-\\infty}^\\infty f_X(x) \\, dx = 1` },
      { id: "prob-10", latex: `\\mathrm{CDF}_X(x) = P(X \\leq x)` },
      { id: "prob-11", latex: `\\mathrm{PDF}_X(x) = \\frac{d}{dx} \\mathrm{CDF}_X(x)` },
    ],
  },
  {
    id: "greek-letters",
    name: "Greek Letters",
    archived: false,
    isPremade: true,
    entries: [
      { id: "greek-alpha", latex: `\\alpha` },
      { id: "greek-beta", latex: `\\beta` },
      { id: "greek-gamma", latex: `\\gamma` },
      { id: "greek-delta", latex: `\\delta` },
      { id: "greek-epsilon", latex: `\\epsilon` },
      { id: "greek-zeta", latex: `\\zeta` },
      { id: "greek-eta", latex: `\\eta` },
      { id: "greek-theta", latex: `\\theta` },
      { id: "greek-iota", latex: `\\iota` },
      { id: "greek-kappa", latex: `\\kappa` },
      { id: "greek-lambda", latex: `\\lambda` },
      { id: "greek-mu", latex: `\\mu` },
      { id: "greek-nu", latex: `\\nu` },
      { id: "greek-xi", latex: `\\xi` },
      { id: "greek-pi", latex: `\\pi` },
      { id: "greek-rho", latex: `\\rho` },
      { id: "greek-sigma", latex: `\\sigma` },
      { id: "greek-tau", latex: `\\tau` },
      { id: "greek-upsilon", latex: `\\upsilon` },
      { id: "greek-phi", latex: `\\phi` },
      { id: "greek-chi", latex: `\\chi` },
      { id: "greek-psi", latex: `\\psi` },
      { id: "greek-omega", latex: `\\omega` },

      // Capital letters
      { id: "greek-Gamma", latex: `\\Gamma` },
      { id: "greek-Delta", latex: `\\Delta` },
      { id: "greek-Theta", latex: `\\Theta` },
      { id: "greek-Lambda", latex: `\\Lambda` },
      { id: "greek-Xi", latex: `\\Xi` },
      { id: "greek-Pi", latex: `\\Pi` },
      { id: "greek-Sigma", latex: `\\Sigma` },
      { id: "greek-Upsilon", latex: `\\Upsilon` },
      { id: "greek-Phi", latex: `\\Phi` },
      { id: "greek-Psi", latex: `\\Psi` },
      { id: "greek-Omega", latex: `\\Omega` },
    ],
  },
  {
    id: "premade-linalg",
    name: "Linear Algebra",
    archived: false,
    isPremade: true,
    entries: [
      { id: "linalg-1", latex: `\\mathbf{v} = \\begin{bmatrix} v_1 \\\\ v_2 \\\\ \\vdots \\\\ v_n \\end{bmatrix}` },
      { id: "linalg-2", latex: `\\mathbf{A} = [a_{ij}]` },
      { id: "linalg-3", latex: `\\mathbf{I}_n` },
      { id: "linalg-4", latex: `\\mathbf{0}` },
      { id: "linalg-5", latex: `\\mathbf{1}` },
      { id: "linalg-6", latex: `\\mathrm{diag}(d_1, d_2, \\dots, d_n)` },
      { id: "linalg-7", latex: `\\mathbf{A} + \\mathbf{B}` },
      { id: "linalg-8", latex: `c\\mathbf{v}` },
      { id: "linalg-9", latex: `\\mathbf{A}\\mathbf{v}` },
      { id: "linalg-10", latex: `\\mathbf{A}\\mathbf{B}` },
      { id: "linalg-11", latex: `\\mathbf{A}^\\top` },
      { id: "linalg-12", latex: `\\mathbf{A}^{-1}` },
      { id: "linalg-13", latex: `\\|\\mathbf{v}\\|` },
      { id: "linalg-14", latex: `\\mathbf{v} \\cdot \\mathbf{w} = \\mathbf{v}^\\top \\mathbf{w}` },
      { id: "linalg-15", latex: `\\mathbf{v} \\otimes \\mathbf{w}` },
      { id: "linalg-16", latex: `\\mathbf{A}\\mathbf{x} = \\mathbf{b}` },
      { id: "linalg-17", latex: `\\mathbf{A}\\mathbf{x} = \\mathbf{0}` },
      { id: "linalg-18", latex: `\\mathrm{rank}(\\mathbf{A})` },
      { id: "linalg-19", latex: `\\mathrm{null}(\\mathbf{A})` },
      { id: "linalg-20", latex: `\\ker(\\mathbf{A})` },
      { id: "linalg-21", latex: `\\mathrm{col}(\\mathbf{A})` },
      { id: "linalg-22", latex: `\\mathrm{row}(\\mathbf{A})` },
      { id: "linalg-23", latex: `\\dim(\\mathrm{null}(\\mathbf{A})) + \\mathrm{rank}(\\mathbf{A}) = n` },
      { id: "linalg-24", latex: `\\mathrm{span}\\{\\mathbf{v}_1, \\dots, \\mathbf{v}_k\\}` },
      { id: "linalg-25", latex: `\\{\\mathbf{v}_1, \\dots, \\mathbf{v}_k\\}` },
      { id: "linalg-26", latex: `\\dim(V)` },
      { id: "linalg-27", latex: `\\mathbf{P}^{-1} \\mathbf{A} \\mathbf{P}` },
      { id: "linalg-28", latex: `[\\mathbf{v}]_{\\mathcal{B}}` },
      { id: "linalg-29", latex: `\\det(\\mathbf{A})` },
      { id: "linalg-30", latex: `\\det(\\mathbf{A}\\mathbf{B}) = \\det(\\mathbf{A})\\det(\\mathbf{B})` },
      { id: "linalg-31", latex: `\\det(\\mathbf{A}^{-1}) = \\frac{1}{\\det(\\mathbf{A})}` },
      { id: "linalg-32", latex: `\\mathbf{A} \\mathbf{v} = \\lambda \\mathbf{v}` },
      { id: "linalg-33", latex: `\\mathrm{eig}(\\mathbf{A})` },
      { id: "linalg-34", latex: `\\mathbf{A} = \\mathbf{PDP}^{-1}` },
      { id: "linalg-35", latex: `\\mathbf{A}^k = \\mathbf{PD}^k \\mathbf{P}^{-1}` },
      { id: "linalg-36", latex: `\\mathrm{trace}(\\mathbf{A}) = \\sum \\lambda_i` },
      { id: "linalg-37", latex: `\\mathrm{proj}_{\\mathbf{u}}(\\mathbf{v}) = \\frac{\\mathbf{u} \\cdot \\mathbf{v}}{\\|\\mathbf{u}\\|^2} \\mathbf{u}` },
      { id: "linalg-38", latex: `\\mathbf{u} \\perp \\mathbf{v}` },
      { id: "linalg-39", latex: `\\mathbf{Q}^\\top \\mathbf{Q} = \\mathbf{I}` },
      { id: "linalg-40", latex: `\\mathbf{P} = \\mathbf{A}(\\mathbf{A}^\\top \\mathbf{A})^{-1} \\mathbf{A}^\\top` },
      { id: "linalg-41", latex: `\\mathbf{A} = \\mathbf{QR}` },
      { id: "linalg-42", latex: `\\mathbf{A} = \\mathbf{LU}` },
      { id: "linalg-43", latex: `\\mathbf{A} = \\mathbf{U} \\Sigma \\mathbf{V}^\\top` },
      { id: "linalg-44", latex: `\\mathbf{x}^\\top \\mathbf{A} \\mathbf{x}` },
      { id: "linalg-45", latex: `\\mathbf{A}^\\top = \\mathbf{A}` },
      { id: "linalg-46", latex: `\\mathbf{A}^\\top = \\mathbf{A}^{-1}` },
      { id: "linalg-47", latex: `\\mathbf{A} = \\mathbf{A}^\\top = \\overline{\\mathbf{A}}` },
      { id: "linalg-48", latex: `A_{ij}` },
      { id: "linalg-49", latex: `\\delta_{ij}` },
      { id: "linalg-50", latex: `\\mathbf{e}_i` },
      { id: "linalg-51", latex: `\\begin{bmatrix} a_{11} & a_{12} & a_{13} \\\\ a_{21} & a_{22} & a_{23} \\end{bmatrix}` },
      { id: "linalg-52", latex: `\\begin{bmatrix} a_{11} & a_{12} \\\\ a_{21} & a_{22} \\\\ a_{31} & a_{32} \\end{bmatrix}` },
      { id: "linalg-53", latex: `\\begin{bmatrix} a_{11} & a_{12} & a_{13} & a_{14} \\\\ a_{21} & a_{22} & a_{23} & a_{24} \\\\ a_{31} & a_{32} & a_{33} & a_{34} \\\\ a_{41} & a_{42} & a_{43} & a_{44} \\end{bmatrix}` },
      { id: "linalg-54", latex: `\\begin{bmatrix} a_{11} & a_{12} & a_{13} & a_{14} & a_{15} \\\\ a_{21} & a_{22} & a_{23} & a_{24} & a_{25} \\\\ a_{31} & a_{32} & a_{33} & a_{34} & a_{35} \\\\ a_{41} & a_{42} & a_{43} & a_{44} & a_{45} \\\\ a_{51} & a_{52} & a_{53} & a_{54} & a_{55} \\end{bmatrix}` },
      { id: "linalg-55", latex: `\\begin{matrix} a_{11} & a_{12} \\\\ a_{21} & a_{22} \\end{matrix}` },
      { id: "linalg-56", latex: `\\begin{pmatrix} a_{11} & a_{12} \\\\ a_{21} & a_{22} \\end{pmatrix}` },
      { id: "linalg-57", latex: `\\begin{bmatrix} a_{11} & a_{12} \\\\ a_{21} & a_{22} \\end{bmatrix}` },
      { id: "linalg-58", latex: `\\begin{Bmatrix} a_{11} & a_{12} \\\\ a_{21} & a_{22} \\end{Bmatrix}` },
      { id: "linalg-59", latex: `\\begin{vmatrix} a_{11} & a_{12} \\\\ a_{21} & a_{22} \\end{vmatrix}` },
      { id: "linalg-60", latex: `\\begin{Vmatrix} a_{11} & a_{12} \\\\ a_{21} & a_{22} \\end{Vmatrix}` },
      { id: "linalg-61", latex: `\\vec{v}` },
    ],
  },
  {
    id: "premade-actuarial",
    name: "Actuarial Science",
    archived: false,
    isPremade: true,
    entries: [
      { id: "actsymb-1", latex: `a(x)` }, // Page 14 of the actuarialsymbol user guide 
      { id: "actsymb-2", latex: `a_x` },
      { id: "actsymb-3", latex: `\\actsymb[][]{a}{\\angl{K}}[]` },
      { id: "actsymb-4", latex: `\\actsymb[][]{\\bar{a}}{\\angl{n}}[]` },
      { id: "actsymb-5", latex: `\\actsymb[][]{\\bar{a}}{{P}_{t}}[]` },
      { id: "actsymb-6", latex: `\\actsymb[][]{\\bar{a}}{\\angl{T}}[]` },
      { id: "actsymb-7", latex: `\\actsymb[][]{\\bar{a}}{x}[]` },
      { id: "actsymb-8", latex: `\\actsymb[][]{\\bar{a}}{r}[h]` },
      { id: "actsymb-9", latex: `\\actsymb[][]{\\bar{a}}{x+t}[r]` },
      { id: "actsymb-10", latex: `\\actsymb[][]{\\ddot{a}}{\\angl{K+1}}[]` },
      { id: "actsymb-11", latex: `\\actsymb[][]{\\ddot{a}}{x}[(m)]` },
      { id: "actsymb-12", latex: `\\actsymb[][]{\\mathring{a}}{x}[(m)]` },
      { id: "actsymb-13", latex: `\\actsymb[][]{\\ddot{a}}{x}[{m}]` },
      { id: "actsymb-14", latex: `\\actsymb[j][]{\\ddot{a}}{x}[]` },
      { id: "actsymb-15", latex: `\\actsymb[*][]{\\ddot{a}}{x}[]` },
      { id: "actsymb-16", latex: `\\actsymb[][]{a}{x:\\angl{n}}[]` },
      { id: "actsymb-17", latex: `\\actsymb[][]{\\bar{a}}{x:\\angl{n}}[]` }, // Page 15 of the actuarialsymbol user guide
      { id: "actsymb-18", latex: `\\actsymb[][]{\\ddot{a}}{x:\\angl{n}}[]` },
      { id: "actsymb-19", latex: `\\actsymb[][]{\\ddot{a}}{x:\\angl{n}}[(m)]` },
      { id: "actsymb-20", latex: `\\actsymb[][]{\\mathring{a}}{x:\\angl{n}}[(m)]` },
      { id: "actsymb-21", latex: `\\actsymb[][]{\\ddot{a}}{x:\\angl{n}}[{m}]` },
      { id: "actsymb-22", latex: `\\actsymb[][]{\\bar{a}}{\\joint{x:\\angl{n}}}[]` },
      { id: "actsymb-23", latex: `\\actsymb[][2]{\\bar{a}}{x:\\angl{n}}[]` },
      { id: "actsymb-24", latex: `\\actsymb[n|][]{a}{x}[]` },
      { id: "actsymb-25", latex: `\\actsymb[n|][]{\\bar{a}}{x}[]` },
      { id: "actsymb-26", latex: `\\actsymb[n|][]{\\ddot{a}}{x}[]` },
      { id: "actsymb-27", latex: `\\actsymb[n|][]{\\ddot{a}}{x}[(m)]` },
      { id: "actsymb-28", latex: `\\actsymb[][]{\\bar{a}}{xy|z}[1]` },
      { id: "actsymb-29", latex: `\\actsymb[][]{\\ddot{a}}{xy}[(m)]` },
      { id: "actsymb-30", latex: `\\actsymb[][]{\\ddot{a}}{xy:\\angl{n}}[]` },
      { id: "actsymb-31", latex: `\\actsymb[][2]{\\ddot{a}}{xy:\\angl{n}}[]` },
      { id: "actsymb-32", latex: `\\actsymb[][]{\\bar{a}}{x|y}[]` },
      { id: "actsymb-33", latex: `\\actsymb[][]{\\bar{a}}{\\joint{{x}_{1}{x}_{2}{x}_{3}}}[]` },
      { id: "actsymb-34", latex: `(aA)(x)` },
      { id: "actsymb-35", latex: `\\actsymb[][]{(aA)}{t}[]` },
      { id: "actsymb-36", latex: `\\actsymb[][]{(aC)}{t}[]` },
      { id: "actsymb-37", latex: `\\actsymb[][]{(aF)}{t}[]` },
      { id: "actsymb-38", latex: `\\actsymb[][]{(aU)}{t}[]` },
      { id: "actsymb-39", latex: `(aV)(x)` },
      { id: "actsymb-40", latex: `\\actsymb[][]{(aV)}{t}[]` },
      { id: "actsymb-41", latex: `A(h)` },
      { id: "actsymb-42", latex: `A_t` },
      { id: "actsymb-43", latex: `\\actsymb[][]{A}{t}[]` },
      { id: "actsymb-44", latex: `\\actsymb[][]{\\bar{A}}{x}[]` },
      { id: "actsymb-45", latex: `\\actsymb[][]{A}{x}[(m)]` },
      { id: "actsymb-46", latex: `\\actsymb[][]{\\bar{A}}{x}[\\text{PR}]` },
      { id: "actsymb-47", latex: `\\actsymb[][]{A}{\\nthtop{1}{x}:\\angl{n}}[]` },
      { id: "actsymb-48", latex: `\\actsymb[][]{A}{\\nthtop{}{x}:\\angl{n}}[]` }, // Page 16 of the actuarialsymbol user guide
      { id: "actsymb-49", latex: `\\actsymb[][]{\\bar{A}}{\\nthtop{}{x}:\\angl{n}}[]` },
      { id: "actsymb-50", latex: `\\actsymb[][]{A}{x:\\nthtop{1}{\\angl{n}}}[]` },
      { id: "actsymb-51", latex: `\\actsymb[j][]{A}{x}[]` },
      { id: "actsymb-52", latex: `\\actsymb[*][]{A}{x}[]` },
      { id: "actsymb-53", latex: `\\actsymb[][]{\\bar{A}}{\\nthtop{1}{x}:\\angl{n}}[]` },
      { id: "actsymb-54", latex: `\\actsymb[][]{\\tilde{A}}{\\nthtop{1}{x}:\\angl{n}}[]` },
      { id: "actsymb-55", latex: `\\actsymb[][2]{A}{x:\\nthtop{1}{\\angl{n}}}[]` },
      { id: "actsymb-56", latex: `\\actsymb[][2]{A}{\\nthtop{1}{x}:\\angl{n}}[]` },
      { id: "actsymb-57", latex: `\\actsymb[m|][]{\\bar{A}}{x}[]` },
      { id: "actsymb-58", latex: `\\actsymb[m|n][]{\\bar{A}}{x}[]` },
      { id: "actsymb-59", latex: `\\actsymb[][]{A}{xy}[]` },
      { id: "actsymb-60", latex: `\\actsymb[][]{A}{\\joint{xy}}[]` },
      { id: "actsymb-61", latex: `\\actsymb[][]{A}{xy}[(m)]` },
      { id: "actsymb-62", latex: `\\actsymb[][]{\\bar{A}}{x\\nthtop{2}{y}}[]` },
      { id: "actsymb-63", latex: `\\actsymb[][]{\\bar{A}}{\\nthtop{1}{x}y}[]` },
      { id: "actsymb-64", latex: `\\actsymb[][]{A}{xy:\\angl{n}}[]` },
      { id: "actsymb-65", latex: `\\actsymb[][]{\\bar{A}}{\\nthtop{1}{\\joint{xy}}:\\angl{n}}[]` },
      { id: "actsymb-66", latex: `\\actsymb[][]{\\bar{A}}{wx\\nthtop{2}{y}}[]` },
      { id: "actsymb-67", latex: `\\actsymb[][]{\\bar{A}}{\\joint{{x}_{1}{x}_{2}{x}_{3}}}[]` },
      { id: "actsymb-68", latex: `\\actsymb[k][]{AS}{}[]` },
      { id: "actsymb-69", latex: `\\actsymb[k][]{\\widehat{AS}}{}[]` },
      { id: "actsymb-70", latex: `\\actsymb[][]{(AS)}{x+h}[]` },
      { id: "actsymb-71", latex: `(AAI)` },
      { id: "actsymb-72", latex: `\\Gamma (\\alpha )` },
      { id: "actsymb-73", latex: `b(u)` },
      { id: "actsymb-74", latex: `b_j` },
      { id: "actsymb-75", latex: `b_t` },
      { id: "actsymb-76", latex: `b_f(t)` }, // Page 17 of the actuarialsymbol user guide
      { id: "actsymb-77", latex: `B_t` },
      { id: "actsymb-78", latex: `\\hat{B}_{x + k}` },
      { id: "actsymb-79", latex: `\\hat{B}_{x + t}^{(3)}` },
      { id: "actsymb-80", latex: `\\hat{B}_{x + t}^{(j)}` },
      { id: "actsymb-81", latex: `\\actsymb[h][]{BP}{}[]` },
      { id: "actsymb-82", latex: `c_k` },
      { id: "actsymb-83", latex: `\\hat{c}_k` },
      { id: "actsymb-84", latex: `c(t)` },
      { id: "actsymb-85", latex: `C_1` },
      { id: "actsymb-86", latex: `C_2` },
      { id: "actsymb-87", latex: `C_3` },
      { id: "actsymb-88", latex: `\\actsymb[k][]{CV}{}[]` },
      { id: "actsymb-89", latex: `\\actsymb[][]{d}{x}[(j)]` },
      { id: "actsymb-90", latex: `\\actsymb[n][]{d}{x}[]` },
      { id: "actsymb-91", latex: `\\actsymb[n][]{d}{x}[(j)]` },
      { id: "actsymb-92", latex: `\\actsymb[n][]{d}{x}[(\\tau )]` },
      { id: "actsymb-93", latex: `\\actsymb[t][]{D}{j}[]` },
      { id: "actsymb-94", latex: `\\actsymb[k+1][]{D}{}[]` },
      { id: "actsymb-95", latex: `{(DA)}_{\\nthtop{1}{x}:\\angl{n}}` },
      { id: "actsymb-96", latex: `{(D\\bar{A})}_{\\nthtop{1}{x}:\\angl{n}}` },
      { id: "actsymb-97", latex: `\\actsymb[n][]{\\mathcal{D}}{x}[]` },
      { id: "actsymb-98", latex: `\\actsymb[n][]{\\mathcal{D}}{x}[(j)]` },
      { id: "actsymb-99", latex: `\\actsymb[n][]{\\mathcal{D}}{x}[(\\tau )]` },
      { id: "actsymb-100", latex: `{e}_{h-1}` },
      { id: "actsymb-101", latex: `e_x` },
      { id: "actsymb-102", latex: `\\actsymb[][]{\\mathring{e}}{x}[]` },
      { id: "actsymb-103", latex: `{\\hat{e}}_{k}` }, // Page 18 of the actuarialsymbol user guide
      { id: "actsymb-104", latex: `\\actsymb[][]{\\mathring{e}}{x:\\angl{n}}[]` },
      { id: "actsymb-105", latex: `{e}_{xy}` },
      { id: "actsymb-106", latex: `{e}_{\\joint{xy}}` },
      { id: "actsymb-107", latex: `E_0` },
      { id: "actsymb-108", latex: `\\actsymb[n][]{E}{x}[]` },
      { id: "actsymb-109", latex: `\\actsymb[][]{(EX)}{x+h+t}[]` },
      { id: "actsymb-110", latex: `ELRA` }, //TODO this and some others need \\mathit to exist, must implement!!
      { id: "actsymb-111", latex: `f(u, t)` },
      { id: "actsymb-112", latex: `f_S(s)` },
      { id: "actsymb-113", latex: `F_X(x)` },
      { id: "actsymb-114", latex: `F_t` },
      { id: "actsymb-115", latex: `{F}^{(k)}` },
      { id: "actsymb-116", latex: `F_S(s)` },
      { id: "actsymb-117", latex: `\\actsymb[k][]{F}{}[]` },
      { id: "actsymb-118", latex: `\\hat{G}` },
      { id: "actsymb-119", latex: `G(b)` },
      { id: "actsymb-120", latex: `G(x;\\alpha ,\\beta )` },
      { id: "actsymb-121", latex: `h(x)` },
      { id: "actsymb-122", latex: `H(r)` },
      { id: "actsymb-123", latex: `H(x;\\alpha ,\\beta ,{x}_{0})` },
      { id: "actsymb-124", latex: `\\actsymb[u][]{(hp)}{x+t}[(\\tau )]` },
      { id: "actsymb-125", latex: `\\actsymb[][]{(h\\mu )}{x+t}[(j)](u)` },
      { id: "actsymb-126", latex: `{i’}_{k+1}` },
      { id: "actsymb-127", latex: `{î}_{k+1}` }, //imperfect
      { id: "actsymb-128", latex: `i(s, s + t)` }, // Page 19 of the actuarialsymbol user guide
      { id: "actsymb-129", latex: `I_k` },
      { id: "actsymb-130", latex: `I_d` },
      { id: "actsymb-131", latex: `I_d(x)` },
      { id: "actsymb-132", latex: `\\actsymb[j][]{i}{k}[]` },
      { id: "actsymb-133", latex: `{(IA)}_{x}` },
      { id: "actsymb-134", latex: `{(I\\bar{A})}_{x}` },
      { id: "actsymb-135", latex: `{(\\bar{I}\\bar{A})}_{x}` },
      { id: "actsymb-136", latex: `\\actsymb[][]{(\\actsymb[][]{I}{}[(m)]\\bar{A})}{x}[]` },
      { id: "actsymb-137", latex: `{(IA)}_{\\nthtop{1}{x}:\\angl{n}}` },
      { id: "actsymb-138", latex: `j(s, s + t, s + u)` },
      { id: "actsymb-139", latex: `\\actsymb[t][]{\\bar{k}}{x}[]` },
      { id: "actsymb-140", latex: `K(x)` },
      { id: "actsymb-141", latex: `K(xy)` },
      { id: "actsymb-142", latex: `K(\\joint{xy})` },
      { id: "actsymb-143", latex: `\\actsymb[][]{l}{x}[]` },
      { id: "actsymb-144", latex: `\\actsymb[][]{l}{[x]+k}[]` },
      { id: "actsymb-145", latex: `\\actsymb[][]{l}{x}[(\\tau )]` },
      { id: "actsymb-146", latex: `l(x, u)` },
      { id: "actsymb-147", latex: `l_f(x, u)` },
      { id: "actsymb-148", latex: `L_1` },
      { id: "actsymb-149", latex: `L_x` },
      { id: "actsymb-150", latex: `L(h)` },
      { id: "actsymb-151", latex: `\\actsymb[t][]{L}{}[]` },
      { id: "actsymb-152", latex: `\\actsymb[t][]{L}{}[\\underline{2}]` },
      { id: "actsymb-153", latex: `\\actsymb[t][]{L}{e}[]` },
      { id: "actsymb-154", latex: `\\actsymb[t][]{L}{e}[\\underline{2}]` },
      { id: "actsymb-155", latex: `\\mathcal{L}(x)` }, // Page 20 of the actuarialsymbol user guide
      { id: "actsymb-156", latex: `\\actsymb[][]{\\mathcal{L}}{x}[(\\tau )]` },
      { id: "actsymb-157", latex: `m(x)` },
      { id: "actsymb-158", latex: `m_x` },
      { id: "actsymb-159", latex: `m_x^{(j)}` },
      { id: "actsymb-160", latex: `m_x^{(\\tau)}` },
      { id: "actsymb-161", latex: `{m}_{x}^{'(j)}` }, //TODO support "\\prime"
      { id: "actsymb-162", latex: `{\\mathrm{M}}_{X}(t)` },
      { id: "actsymb-163", latex: `M(x)` },
      { id: "actsymb-164", latex: `n(u)` },
      { id: "actsymb-165", latex: `N(t)` },
      { id: "actsymb-166", latex: `p(j)` },
      { id: "actsymb-167", latex: `p(x)` },
      { id: "actsymb-168", latex: `p_k` },
      { id: "actsymb-169", latex: `\\actsymb[][]{p}{[x]+r}[]` },
      { id: "actsymb-170", latex: `\\actsymb[][]{p}{}[*n](x)` },
      { id: "actsymb-171", latex: `\\actsymb[t][]{p}{x}[]` },
      { id: "actsymb-172", latex: `\\actsymb[t][]{p}{x}[(\\tau )]` },
      { id: "actsymb-173", latex: `\\actsymb[t][]{p}{x}['(j)]` }, //TODO \\prime`
      { id: "actsymb-174", latex: `\\actsymb[t][]{p}{xy}[]` },
      { id: "actsymb-175", latex: `\\actsymb[t][]{p}{\\joint{xy}}[]` },
      { id: "actsymb-176", latex: `\\actsymb[u][]{p}{\\joint{xy}+t}[]` },
      { id: "actsymb-177", latex: `\\actsymb[t][]{p}{\\joint{{x}_{1}{x}_{2}\\nthtop{k}{{x}_{3}}}}[]` },
      { id: "actsymb-178", latex: `P(x)` },
      { id: "actsymb-179", latex: `P(s, t)` },
      { id: "actsymb-180", latex: `P_t` },
      { id: "actsymb-181", latex: `\\actsymb[][T]{P}{t}[]` },
      { id: "actsymb-182", latex: `P^a` },
      { id: "actsymb-183", latex: `P_x` },
      { id: "actsymb-184", latex: `\\actsymb[j][]{P}{x}[]` }, // Page 21 of the actuarialsymbol user guide`
      { id: "actsymb-185", latex: `\\actsymb[*][]{P}{x}[]` },
      { id: "actsymb-186", latex: `\\actsymb[][]{P}{x:\\angl{n}}[A]` },
      { id: "actsymb-187", latex: `\\actsymb[][]{P}{x:\\angl{n}}[]` },
      { id: "actsymb-188", latex: `\\actsymb[][]{P}{\\joint{xy}}[]` },
      { id: "actsymb-189", latex: `\\actsymb[][]{P}{\\nthtop{1}{x}:\\angl{n}}[]` }, // TODO what is `\\:` in the guide?
      { id: "actsymb-190", latex: `\\actsymb[][]{P}{x:\\nthtop{1}{\\angl{n}}}[]` },
      { id: "actsymb-191", latex: `\\actsymb[][]{P}{}[*n](x)` },
      { id: "actsymb-192", latex: `\\actsymb[h][]{P}{x}[]` },
      { id: "actsymb-193", latex: `\\actsymb[h][]{P}{x:\\angl{n}}[]` },
      { id: "actsymb-194", latex: `(Pa)(x)` }, // semantic mismatch w guide
      { id: "actsymb-195", latex: `(Pa)_t` }, // semantic mismatch w guide
      { id: "actsymb-196", latex: `\\actsymb[][]{P}{}[](\\actsymb[][]{\\bar{A}}{x:\\angl{n}}[])` },
      { id: "actsymb-197", latex: `\\actsymb[][]{P}{}[](\\actsymb[n|][]{\\ddot{a}}{x}[])` },
      { id: "actsymb-198", latex: `\\actsymb[][]{P}{}[](\\actsymb[n|][]{\\bar{a}}{x}[])` },
      { id: "actsymb-199", latex: `\\actsymb[][]{P}{}[(m)](\\actsymb[][]{\\bar{A}}{x}[])` },
      { id: "actsymb-200", latex: `\\actsymb[][]{P}{}[\\{m\\}](\\actsymb[][]{\\bar{A}}{x}[])` },
      { id: "actsymb-201", latex: `\\actsymb[][]{P}{}[](\\actsymb[][]{\\bar{A}}{x}[PR])` },
      { id: "actsymb-202", latex: `\\actsymb[][]{\\bar{P}}{}[](\\actsymb[][]{\\bar{A}}{x:\\angl{n}}[])` },
      { id: "actsymb-203", latex: `\\actsymb[][]{\\bar{P}}{}[](\\actsymb[][]{\\bar{A}}{\\nthtop{1}{x}:\\angl{n}}[])` },
      { id: "actsymb-204", latex: `\\actsymb[][]{\\bar{P}}{}[](\\actsymb[][]{\\bar{A}}{x:\\nthtop{1}{\\angl{n}}}[])` },
      { id: "actsymb-205", latex: `\\actsymb[][]{P}{}[(m)](\\actsymb[][]{\\bar{A}}{\\nthtop{}{x}:\\angl{n}}[])` },
      { id: "actsymb-206", latex: `\\actsymb[][]{P}{}[(m)](\\actsymb[][]{\\bar{A}}{\\nthtop{1}{x}:\\angl{n}}[])        ` },
      { id: "actsymb-207", latex: `\\actsymb[h][]{\\bar{P}}{}[](\\actsymb[][]{\\bar{A}}{x}[])` },
      { id: "actsymb-208", latex: `\\actsymb[h][]{\\bar{P}}{}[](\\actsymb[][]{\\bar{A}}{x:\\angl{n}}[])` },
      { id: "actsymb-209", latex: `\\actsymb[h][]{P}{}[(m)](\\actsymb[][]{\\bar{A}}{x}[])` },
      { id: "actsymb-210", latex: `\\actsymb[h][]{P}{}[(m)]\\actsymb[][]{\\bar{A}}{x:\\angl{n}}[]` },
      { id: "actsymb-211", latex: `\\actsymb[h][]{P}{}[{m}](\\actsymb[][]{\\bar{A}}{x:\\angl{n}}[])` },
      { id: "actsymb-212", latex: `\\actsymb[][]{P}{}[](\\actsymb[][]{\\bar{A}}{\\joint{xy\\nthtop{2}{z}}}[])` },
      { id: "actsymb-213", latex: `\\actsymb[][]{P}{}[](\\actsymb[][]{\\bar{A}}{\\joint{x\\nthtop{2}{y}z}}[])` },
      { id: "actsymb-214", latex: `\\actsymb[][]{\\tilde{P}}{\\nthtop{1}{x}:\\angl{n}}[]` }, //TODO `\\:`
      { id: "actsymb-215", latex: `\\actsymb[][]{q}{[x]+r}[]` }, // Page 22 of the actuarialsymbol user guide
      { id: "actsymb-216", latex: `\\actsymb[][]{q}{x}[(d)]` },
      { id: "actsymb-217", latex: `\\actsymb[][]{q}{x}[(i)]` },
      { id: "actsymb-218", latex: `\\actsymb[][]{q}{x}[(r)]` },
      { id: "actsymb-219", latex: `\\actsymb[][]{q}{x}[(w)]` },
      { id: "actsymb-220", latex: `\\actsymb[][]{\\hat{q}}{x+k}[(j)]` },
      { id: "actsymb-221", latex: `\\actsymb[][]{q}{xy}[]` },
      { id: "actsymb-222", latex: `\\actsymb[k|][]{q}{x}[]` },
      { id: "actsymb-223", latex: `\\actsymb[t][]{q}{x}[]` },
      { id: "actsymb-224", latex: `\\actsymb[t][]{q}{x}['(j)]` }, //TODO prime
      { id: "actsymb-225", latex: `\\actsymb[t|u][]{q}{x}[]` },
      { id: "actsymb-226", latex: `\\actsymb[n][]{q}{\\nthtop{1}{x}y}[]` },
      { id: "actsymb-227", latex: `\\actsymb[n][]{q}{x\\nthtop{2}{y}}[]` },
      { id: "actsymb-228", latex: `\\actsymb[k|][]{q}{xy}[]` },
      { id: "actsymb-229", latex: `\\actsymb[n][]{q}{\\nthbottom{1}{x}\\nthtop{2}{y}z}[]` },
      { id: "actsymb-230", latex: `\\actsymb[\\infty ][]{q}{\\nthbottom{1}{x}\\nthbottom{2}{y}\\nthtop{3}{z}}[]` },
      { id: "actsymb-231", latex: `r_C` },
      { id: "actsymb-232", latex: `r_F` },
      { id: "actsymb-233", latex: `r_N` },
      { id: "actsymb-234", latex: `\\actsymb[][]{(rA)}{t}[]` },
      { id: "actsymb-235", latex: `\\actsymb[][]{(rF)}{t}[]` },
      { id: "actsymb-236", latex: `\\actsymb[][]{(rV)}{t}[]` },
      { id: "actsymb-237", latex: `\\tilde{R}` },
      { id: "actsymb-238", latex: `R(x, h, y)` },
      { id: "actsymb-239", latex: `s(x)` },
      { id: "actsymb-240", latex: `\\actsymb[][]{\\ddot{s}}{\\angl{n}}[]` }, // Page 23 of the actuarialsymbol user guide
      { id: "actsymb-241", latex: `s(x,u)` },
      { id: "actsymb-242", latex: `\\actsymb[][]{\\bar{s}}{x:\\angl{n}}[]` },
      { id: "actsymb-243", latex: `\\actsymb[][]{\\ddot{s}}{x:\\angl{n}}[]` },
      { id: "actsymb-244", latex: `S(t)` },
      { id: "actsymb-245", latex: `S_y` },
      { id: "actsymb-246", latex: `\\actsymb[k][]{SC}{}[]` },
      { id: "actsymb-247", latex: `\\tilde{T}` },
      { id: "actsymb-248", latex: `T_x` },
      { id: "actsymb-249", latex: `{T}_{xy}` },
      { id: "actsymb-250", latex: `{T}_{\\joint{xy}}` },
      { id: "actsymb-251", latex: `U(t)` },
      { id: "actsymb-252", latex: `\\hat{U}{t}` },
      { id: "actsymb-253", latex: `v_t` },
      { id: "actsymb-254", latex: `\\tilde{v}_n` },
      { id: "actsymb-255", latex: `V_i` },
      { id: "actsymb-256", latex: `V_t` },
      { id: "actsymb-257", latex: `\\actsymb[k][]{V}{x}[]` },
      { id: "actsymb-258", latex: `\\actsymb[k][]{V}{x:\\angl{n}}[]` },
      { id: "actsymb-259", latex: `\\actsymb[k][]{V}{\\nthtop{1}{x}:\\angl{n}}[]` }, //TODO \\:
      { id: "actsymb-260", latex: `\\actsymb[k][]{V}{x:\\nthtop{1}{\\angl{n}}}[]` },
      { id: "actsymb-261", latex: `\\actsymb[k][]{V}{x}[\\text{FPT}]` },
      { id: "actsymb-262", latex: `\\actsymb[t][]{V}{\\nthtop{1}{\\group{xy}}:\\angl{n}}[]` }, //TODO missing: \\group{xy} FILL IN THE MISSING ONE` },
      { id: "actsymb-263", latex: `\\actsymb[k][h]{V}{x}[]` },
      { id: "actsymb-264", latex: `\\actsymb[k][h]{V}{x:\\angl{n}}[]` },
      { id: "actsymb-265", latex: `\\actsymb[k][h]{V}{x:\\angl{n}}[(m)]` },
      { id: "actsymb-266", latex: `\\actsymb[k][h]{V}{x:\\angl{n}}[\\text{MOD}]` },
      { id: "actsymb-267", latex: `\\actsymb[k][]{V}{}[](\\actsymb[n|][]{\\ddot{a}}{x}[])` }, // Page 24 of the actuarialsymbol user guide
      { id: "actsymb-268", latex: `\\actsymb[t][]{\\bar{V}}{}[](\\actsymb[n|][]{\\bar{a}}{x}[])` },
      { id: "actsymb-269", latex: `\\actsymb[t][]{\\bar{V}}{}[](\\actsymb[][]{\\bar{A}}{x}[])` },
      { id: "actsymb-270", latex: `\\actsymb[t][]{\\bar{V}}{}[](\\actsymb[][]{\\bar{A}}{x:\\angl{n}}[])` },
      { id: "actsymb-271", latex: `\\actsymb[t][]{\\bar{V}}{}[](\\actsymb[][]{\\bar{A}}{\\nthtop{1}{x}:\\angl{n}}[])` },
      { id: "actsymb-272", latex: `\\actsymb[t][]{\\bar{V}}{}[](\\actsymb[][]{\\bar{A}}{x:\\nthtop{1}{\\angl{n}}}[])` },
      { id: "actsymb-273", latex: `\\actsymb[t][]{\\bar{V}}{}[]{(\\actsymb[][]{\\bar{A}}{x}[])}^{\\text{MOD}}` },
      { id: "actsymb-274", latex: `\\actsymb[t][]{V}{}[](\\actsymb[][]{\\bar{A}}{\\joint{xy}}[])` },
      { id: "actsymb-275", latex: `\\actsymb[t][]{V}{}[{1}](\\actsymb[][]{\\bar{A}}{x}[])` },
      { id: "actsymb-276", latex: `\\actsymb[k][]{V}{}[](\\actsymb[][]{\\bar{A}}{x}[\\text{PR}])` },
      { id: "actsymb-277", latex: `\\actsymb[k][h]{V}{}[](\\actsymb[][]{\\bar{A}}{\\nthtop{1}{x}:\\angl{n}}[])` },
      { id: "actsymb-278", latex: `\\actsymb[t][h]{\\bar{V}}{}[](\\actsymb[][]{\\bar{A}}{x}[])` },
      { id: "actsymb-279", latex: `\\actsymb[t][h]{\\bar{V}}{}[](\\actsymb[][]{\\bar{A}}{x:\\angl{n}}[])` },
      { id: "actsymb-280", latex: `\\actsymb[t][h]{\\bar{V}}{}[(m)](\\actsymb[][]{\\bar{A}}{x:\\angl{n}}[])` },
      { id: "actsymb-281", latex: `w(x)` },
      { id: "actsymb-282", latex: `W_i` },
      { id: "actsymb-283", latex: `W_t` },
      { id: "actsymb-284", latex: `\\actsymb[k][]{W}{}[]` },
      { id: "actsymb-285", latex: `\\actsymb[k][]{W}{x}[]` },
      { id: "actsymb-286", latex: `\\actsymb[k][]{W}{x:\\angl{n}}[]` },
      { id: "actsymb-287", latex: `\\actsymb[k][h]{W}{x}[]` },
      { id: "actsymb-288", latex: `(Wa)_t` },
      { id: "actsymb-289", latex: `\\actsymb[k][]{\\bar{W}}{}[](\\actsymb[][]{A}{x}[])` },
      { id: "actsymb-290", latex: `\\actsymb[k][]{\\bar{W}}{}[](\\actsymb[][]{A}{x:\\angl{n}}[])` },
      { id: "actsymb-291", latex: `\\actsymb[k][h]{\\bar{W}}{}[](\\actsymb[][]{A}{x}[])` },
      { id: "actsymb-292", latex: `(x)` },
      { id: "actsymb-293", latex: `(x_1 x_2 \\dotsm x_m)` },
      { id: "actsymb-294", latex: `(\\joint{x_1 x_2 \\dotsm x_m})` },
      { id: "actsymb-295", latex: `\\joint{x_1x_2 \\dotsm}\\nthtop{k}{\\joint{x_m}}` },
      { id: "actsymb-296", latex: `\\joint{x_1x_2 \\dotsm}\\nthtop{[k]}{\\joint{x_m}}` }, // Page 25 of the actuarialsymbol user guide
      { id: "actsymb-297", latex: `X_i` },
      { id: "actsymb-298", latex: `X(\\theta)` },
      { id: "actsymb-299", latex: `y(s, s + m)` },
      { id: "actsymb-300", latex: `Y(t, n)` },
      { id: "actsymb-301", latex: `z_t` },
      { id: "actsymb-302", latex: `\\actsymb[m][]{Z}{t}[]` },
      { id: "actsymb-303", latex: `\\alpha` },
      { id: "actsymb-304", latex: `\\alpha(m)` },
      { id: "actsymb-305", latex: `\\bar{\\alpha}` },
      { id: "actsymb-306", latex: `\\alpha^{\\text{CRVM}}` },
      { id: "actsymb-307", latex: `\\beta` },
      { id: "actsymb-308", latex: `\\beta(m)` },
      { id: "actsymb-309", latex: `\\bar{\\beta}` },
      { id: "actsymb-310", latex: `\\beta^{\\text{CRVM}}` },
      { id: "actsymb-311", latex: `\\beta(x, u)` },
      { id: "actsymb-312", latex: `\\Gamma(\\alpha)` },
      { id: "actsymb-313", latex: `\\delta` },
      { id: "actsymb-314", latex: `\\delta_t` },
      { id: "actsymb-315", latex: `\\theta` },
      { id: "actsymb-316", latex: `\\lambda(t)` },
      { id: "actsymb-317", latex: `\\lambda(t, n)` },
      { id: "actsymb-318", latex: `\\Lambda` },
      { id: "actsymb-319", latex: `\\Lambda_h` },
      { id: "actsymb-320", latex: `\\mu(x)` },
      { id: "actsymb-321", latex: `\\mu_x(t)` },
      { id: "actsymb-322", latex: `\\mu_x^{(d)}` }, // Page 26 of the actuarialsymbol user guide
      { id: "actsymb-323", latex: `\\mu_x^{(i)}` },
      { id: "actsymb-324", latex: `\\mu_x^{(w)}` },
      { id: "actsymb-325", latex: `\\mu_x^{(j)}(t)` },
      { id: "actsymb-326", latex: `\\mu_x^{(\\tau)}(t)` },
      { id: "actsymb-327", latex: `\\mu_{xy}(t)` },
      { id: "actsymb-328", latex: `\\mu_{\\joint{xy}}(t)` },
      { id: "actsymb-329", latex: `\\mu(x, u)` },
      { id: "actsymb-330", latex: `\\pi_h` },
      { id: "actsymb-331", latex: `\\pi_t` },
      { id: "actsymb-332", latex: `\\rho` },
      { id: "actsymb-333", latex: `\\tau` },
      { id: "actsymb-334", latex: `\\phi(x)` },
      { id: "actsymb-335", latex: `\\phi(x, u)` },
      { id: "actsymb-336", latex: `\\Psi(u)` },
      { id: "actsymb-337", latex: `\\tilde{\\Psi}(u)` },
      { id: "actsymb-338", latex: `\\Psi(u, t)` },
      { id: "actsymb-339", latex: `\\Psi(u; w)` },
      { id: "actsymb-340", latex: `\\tilde{\\Psi}(u; w)` },
      { id: "actsymb-341", latex: `\\omega` },

    ],
  },
];
